import type { Metadata } from "next";
import ThemeRegistry from "../theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "@benbeck764/react-components",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <div>{children}</div>
        </ThemeRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
